services:
  # 1) Serviço PHP‑FPM
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: projfipe_php
    environment:
      JWT_SECRET_KEY: /var/www/html/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/html/config/jwt/public.pem
      JWT_PASSPHRASE: 1234
    volumes:
      - ./projfipe2:/var/www/html
    networks:
      - app-network

  # 2) Servidor web Nginx
  nginx:
    image: nginx:alpine
    container_name: projfipe_nginx
    ports:
      - "8080:80"
    volumes:
      - ./projfipe2:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app-network

  # 3) Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: projfipe_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonypass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # 4) Gerenciador de banco (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: projfipe_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
