services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - symfony

  php:
    build:
      context: ./docker/php
    container_name: php_fpm
    volumes:
      - ./symfony:/var/www/html:cached
    environment:
      - APP_ENV=dev
    networks:
      - symfony

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
    driver: bridge
